name: Release

on:
  push:
    tags:
      - "v*.*"

jobs:
  test-darwin:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Cache ~/.stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}
      - name: Install build prerequisites
        run: brew install argp-standalone haskell-stack protobuf-c util-linux
      - name: Install GHC && build dependencies
        run: cd ${{ github.workspace }}/compiler && make package.yaml && stack build --only-dependencies
      - name: Build actonc
        run: make -C ${{ github.workspace }}
      - name: Build a release
        run: make -C ${{ github.workspace }} release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: acton-darwin
          path: ${{ github.workspace }}/acton-darwin-x86_64*
      - name: Run tests
        run: make -C ${{ github.workspace }} test

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Cache ~/.stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}
      - name: Install build prerequisites
        run: sudo apt-get install -qy alex gcc happy haskell-stack libkqueue-dev libprotobuf-c-dev libutf8proc-dev make
      - name: Install GHC && build dependencies
        run: cd ${{ github.workspace }}/compiler && make package.yaml && stack build --only-dependencies
      - name: Build actonc
        run: make -C ${{ github.workspace }}
      - name: Build a release
        run: make -C ${{ github.workspace }} release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: acton-linux
          path: ${{ github.workspace }}/acton-linux-x86_64*
      - name: Run tests
        run: make -C ${{ github.workspace }} test

  release:
    runs-on: ubuntu-latest
    needs: [test-darwin, test-linux]
    steps:
      - run: echo "Doing a release, yay! 🎉"
      - name: "Check out repository code"
        uses: actions/checkout@v2
      - name: "Download artifacts for darwin"
        uses: actions/download-artifact@v2
        with:
          name: acton-darwin
      - name: "Download artifacts for linux"
        uses: actions/download-artifact@v2
        with:
          name: acton-linux
      - name: "Extract release notes"
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: "Create release"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: acton*.tar*
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
