on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: ${{ startsWith(github.head_ref, 'release-') && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
      - name: "Check out repository code"
        uses: actions/checkout@v2
      - name: "Get the version"
        id: get_version
        run: echo ::set-output name=version::$(grep VERSION= common.mk | cut -d = -f 2)
      - name: "Add version tag and push"
        run: |
          git tag v${{steps.get_version.outputs.version}}
          git push origin v${{steps.get_version.outputs.version}}
